
//
// tokens.h
//

// Do not edit directly
// Generated on Fri, 08 Jul 2022 18:26:44 GMT


#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>

#define BrkButtonOutlineColorFocusStandard #192872
#define BrkButtonOutlineColorFocusInverted #abb6ed
#define BrkButtonOpacityDisabled 50%
#define BrkButtonPrimaryBorderWidth 0
#define BrkButtonSecondaryBorderWidth 2
#define BrkButtonTertiaryBorderWidth 0
#define BrkButtonIconBorderWidth 0
#define BrkButtonOutlineWidth 2
#define BrkButtonTertiaryBoxShadowDefaultStandardX 0
#define BrkButtonTertiaryBoxShadowDefaultStandardY 0
#define BrkButtonTertiaryBoxShadowDefaultStandardBlur 0
#define BrkButtonTertiaryBoxShadowDefaultStandardSpread 0
#define BrkButtonTertiaryBoxShadowDefaultStandardColor #000000
#define BrkButtonTertiaryBoxShadowDefaultStandardType dropShadow
#define BrkButtonTertiaryBoxShadowDefaultInvertedX 0
#define BrkButtonTertiaryBoxShadowDefaultInvertedY 0
#define BrkButtonTertiaryBoxShadowDefaultInvertedBlur 0
#define BrkButtonTertiaryBoxShadowDefaultInvertedSpread 0
#define BrkButtonTertiaryBoxShadowDefaultInvertedColor #000000
#define BrkButtonTertiaryBoxShadowDefaultInvertedType dropShadow
#define BrkButtonTertiaryBoxShadowHoverStandardX 0
#define BrkButtonTertiaryBoxShadowHoverStandardY 0
#define BrkButtonTertiaryBoxShadowHoverStandardBlur 0
#define BrkButtonTertiaryBoxShadowHoverStandardSpread 0
#define BrkButtonTertiaryBoxShadowHoverStandardColor #000000
#define BrkButtonTertiaryBoxShadowHoverStandardType dropShadow
#define BrkButtonTertiaryBoxShadowHoverInvertedX 0
#define BrkButtonTertiaryBoxShadowHoverInvertedY 0
#define BrkButtonTertiaryBoxShadowHoverInvertedBlur 0
#define BrkButtonTertiaryBoxShadowHoverInvertedSpread 0
#define BrkButtonTertiaryBoxShadowHoverInvertedColor #000000
#define BrkButtonTertiaryBoxShadowHoverInvertedType dropShadow
#define BrkButtonTertiaryBoxShadowActiveStandardX 0
#define BrkButtonTertiaryBoxShadowActiveStandardY 0
#define BrkButtonTertiaryBoxShadowActiveStandardBlur 0
#define BrkButtonTertiaryBoxShadowActiveStandardSpread 0
#define BrkButtonTertiaryBoxShadowActiveStandardColor #000000
#define BrkButtonTertiaryBoxShadowActiveStandardType dropShadow
#define BrkButtonTertiaryBoxShadowActiveInvertedX 0
#define BrkButtonTertiaryBoxShadowActiveInvertedY 0
#define BrkButtonTertiaryBoxShadowActiveInvertedBlur 0
#define BrkButtonTertiaryBoxShadowActiveInvertedSpread 0
#define BrkButtonTertiaryBoxShadowActiveInvertedColor #000000
#define BrkButtonTertiaryBoxShadowActiveInvertedType dropShadow
#define BrkButtonTertiaryBoxShadowFocusStandardX 0
#define BrkButtonTertiaryBoxShadowFocusStandardY 0
#define BrkButtonTertiaryBoxShadowFocusStandardBlur 0
#define BrkButtonTertiaryBoxShadowFocusStandardSpread 0
#define BrkButtonTertiaryBoxShadowFocusStandardColor #000000
#define BrkButtonTertiaryBoxShadowFocusStandardType dropShadow
#define BrkButtonTertiaryBoxShadowFocusInvertedX 0
#define BrkButtonTertiaryBoxShadowFocusInvertedY 0
#define BrkButtonTertiaryBoxShadowFocusInvertedBlur 0
#define BrkButtonTertiaryBoxShadowFocusInvertedSpread 0
#define BrkButtonTertiaryBoxShadowFocusInvertedColor #000000
#define BrkButtonTertiaryBoxShadowFocusInvertedType dropShadow
#define BrkButtonBorderRadius 4
#define BrkButtonTertiaryLabelFontFamily Graphik
#define BrkButtonTertiaryLabelFontWeight Medium
#define BrkButtonTertiaryLabelLineHeight 85%
#define BrkButtonTertiaryLabelFontSize 12
#define BrkButtonTertiaryLabelLetterSpacing 2%
#define BrkButtonTertiaryLabelParagraphSpacing 0
#define BrkButtonTertiaryLabelTextCase uppercase
#define BrkButtonTertiaryLabelTextDecoration none
#define BrkButtonTertiaryPaddingTop 10
#define BrkButtonTertiaryPaddingRight 15
#define BrkButtonTertiaryPaddingBottom 10
#define BrkButtonTertiaryPaddingLeft 15
#define BrkButtonTertiaryFontColorDefaultStandard #253aa7
#define BrkButtonTertiaryFontColorDefaultInverted #ffffff
#define BrkButtonTertiaryBackgroundColorDefaultStandard #eaedfa
#define BrkButtonTertiaryBackgroundColorDefaultInverted #203392
#define BrkButtonTertiaryBorderColorDefaultStandard transparent
#define BrkButtonTertiaryBorderColorDefaultInverted transparent
#define BrkButtonTertiaryFontColorHoverStandard #ffffff
#define BrkButtonTertiaryFontColorHoverInverted #ffffff
#define BrkButtonTertiaryBackgroundColorHoverStandard #2e49d1
#define BrkButtonTertiaryBackgroundColorHoverInverted #2e49d1
#define BrkButtonTertiaryBorderColorHoverStandard transparent
#define BrkButtonTertiaryBorderColorHoverInverted transparent
#define BrkButtonTertiaryFontColorActiveStandard #253aa7
#define BrkButtonTertiaryFontColorActiveInverted #ffffff
#define BrkButtonTertiaryBackgroundColorActiveStandard #eaedfa
#define BrkButtonTertiaryBackgroundColorActiveInverted #203392
#define BrkButtonTertiaryBorderColorActiveStandard transparent
#define BrkButtonTertiaryBorderColorActiveInverted transparent
#define BrkButtonTertiaryFontColorFocusStandard #ffffff
#define BrkButtonTertiaryFontColorFocusInverted #ffffff
#define BrkButtonTertiaryBackgroundColorFocusStandard #2e49d1
#define BrkButtonTertiaryBackgroundColorFocusInverted #2e49d1
#define BrkButtonTertiaryBorderColorFocusStandard transparent
#define BrkButtonTertiaryBorderColorFocusInverted transparent
#define BrkJackpotHeroHeadingFontFamily Graphik
#define BrkJackpotHeroHeadingFontWeight Regular
#define BrkJackpotHeroHeadingLineHeight 100%
#define BrkJackpotHeroHeadingFontSize 12
#define BrkJackpotHeroHeadingLetterSpacing 2%
#define BrkJackpotHeroHeadingParagraphSpacing 0
#define BrkJackpotHeroHeadingTextCase uppercase
#define BrkJackpotHeroHeadingTextDecoration none
#define BrkJackpotHeroBodyFontFamily Graphik
#define BrkJackpotHeroBodyFontWeight Medium
#define BrkJackpotHeroBodyLineHeight 100%
#define BrkJackpotHeroBodyFontSize 13
#define BrkJackpotHeroBodyLetterSpacing 0%
#define BrkJackpotHeroBodyParagraphSpacing 0
#define BrkJackpotHeroBodyTextCase none
#define BrkJackpotHeroBodyTextDecoration none
#define BrkJackpotHeroPaddingTop 12
#define BrkJackpotHeroPaddingRight 12
#define BrkJackpotHeroPaddingBottom 12
#define BrkJackpotHeroPaddingLeft 12
#define BrkJackpotHeroHeadingFontColorStandard #eaedfa
#define BrkJackpotHeroBodyFontColorStandard #000000
#define BrkJackpotHeroBodyFontColorInverted #ffffff
#define BrkJackpotHeroBodyBoxBackgroundColorStandard #ffffff
#define BrkJackpotHeroBodyBoxBorderColorStandard transparent
#define BrkJackpotHeroBackgroundColorStandard #121d54
#define BrkJackpotHeroBodyBoxMarginSm 1
#define BrkJackpotHeroBodyBoxMarginMd 4
#define BrkJackpotHeroBodyBoxBorderRadius 1
#define BrkJackpotHeroBodyBoxBorderWidth 0
#define BrkCardHeroSubheadingFontFamily Graphik
#define BrkCardHeroSubheadingFontWeight Bold
#define BrkCardHeroSubheadingLineHeight 85%
#define BrkCardHeroSubheadingFontSize 9
#define BrkCardHeroSubheadingLetterSpacing 2%
#define BrkCardHeroSubheadingParagraphSpacing 0
#define BrkCardHeroSubheadingTextCase uppercase
#define BrkCardHeroSubheadingTextDecoration none
#define BrkCardHeroHeadingFontFamily Graphik
#define BrkCardHeroHeadingFontWeight Medium
#define BrkCardHeroHeadingLineHeight 100%
#define BrkCardHeroHeadingFontSize 16
#define BrkCardHeroHeadingLetterSpacing -2%
#define BrkCardHeroHeadingParagraphSpacing 0
#define BrkCardHeroHeadingTextCase none
#define BrkCardHeroHeadingTextDecoration none
#define BrkCardHeroBodyFontFamily Graphik
#define BrkCardHeroBodyFontWeight Medium
#define BrkCardHeroBodyLineHeight 85%
#define BrkCardHeroBodyFontSize 10
#define BrkCardHeroBodyLetterSpacing 2%
#define BrkCardHeroBodyParagraphSpacing 0
#define BrkCardHeroBodyTextCase none
#define BrkCardHeroBodyTextDecoration none
#define BrkCardHeroHeadingFontColorStandard #2e49d1
#define BrkCardHeroSubheadingFontColorStandard #192872
#define BrkCardHeroBodyFontColorStandard #192872
#define BrkCardHeroBackgroundColorStandard #ffffff
#define BrkCardHeroBorderColorStandard transparent
#define BrkCardHeroPaddingTop 12
#define BrkCardHeroPaddingRight 12
#define BrkCardHeroPaddingBottom 20
#define BrkCardHeroPaddingLeft 12
#define BrkCardHeroHeadingMarginRight 12
#define BrkCardHeroBorderRadiusTopLeft 4
#define BrkCardHeroBorderRadiusTopRight 4
#define BrkCardHeroBorderRadiusBottomRight 4
#define BrkCardHeroBorderRadiusBottomLeft 4
#define BrkCardHeroBorderWidth 0
#define BrkCardHeroBoxShadowDefaultStandardX 0
#define BrkCardHeroBoxShadowDefaultStandardY 2
#define BrkCardHeroBoxShadowDefaultStandardBlur 8
#define BrkCardHeroBoxShadowDefaultStandardSpread 0
#define BrkCardHeroBoxShadowDefaultStandardColor #e6e6e6
#define BrkCardHeroBoxShadowDefaultStandardType dropShadow
#define BrkDocBackgroundColorStandard #f9f9f9
#define BrkDocBackgroundColorInverted #090f2a
#define BrkCardHeroImageBorderRadiusTopLeft 4
#define BrkCardHeroImageBorderRadiusTopRight 4
#define BrkCardHeroImageBorderRadiusBottomRight 0
#define BrkCardHeroImageBorderRadiusBottomLeft 0
#define BrkBodyBoxPaddingTop 4
#define BrkBodyBoxPaddingRight 2
#define BrkBodyBoxPaddingBottom 4
#define BrkBodyBoxPaddingLeft 2
#define BrkOptColorNeutral0 #ffffff
#define BrkOptColorNeutral25 #f9f9f9
#define BrkOptColorNeutral50 #f2f2f2
#define BrkOptColorNeutral100 #e6e6e6
#define BrkOptColorNeutral675 #535353
#define BrkOptColorNeutral900 #1a1a1a
#define BrkOptColorNeutral1000 #000000
#define BrkOptColorNeutralSaturation 0
#define BrkOptColorNeutralHue 0
#define BrkOptColorLqMain50 #eaedfa
#define BrkOptColorLqMain100 #d5dbf6
#define BrkOptColorLqMain200 #abb6ed
#define BrkOptColorLqMain500 #2e49d1
#define BrkOptColorLqMain600 #253aa7
#define BrkOptColorLqMain650 #203392
#define BrkOptColorLqMain728 #192872
#define BrkOptColorLqMain800 #121d54
#define BrkOptColorLqMain900 #090f2a
#define BrkOptColorLqMainSaturation 64
#define BrkOptColorLqMainHue 230
#define BrkOptColorMojMain #db1f1f
#define BrkOptColorMojMainWeb #e41f1f
#define BrkOptColorMojSecond #c9ff00
#define BrkOptColorJelMain #0b5db7
#define BrkOptColorJelSecond #24c1ff
#define BrkOptColorJelThird #a6ecff
#define BrkOptColorJelAccent #fdfe8b
#define BrkOptFontFamilyBrandLq Graphik
#define BrkOptFontFamilyBrandMoj Druk LQ
#define BrkOptLineHeightXs 85%
#define BrkOptLineHeightSm 100%
#define BrkOptLineHeightMd 110%
#define BrkOptLineHeightLg 120%
#define BrkOptLineHeightXl 160%
#define BrkOptFontWeightRegular Regular
#define BrkOptFontWeightMedium Medium
#define BrkOptFontWeightBold Bold
#define BrkOptFontWeightHeavy Heavy
#define BrkOptFontSizeCaption8 8
#define BrkOptFontSizeCaption9 9
#define BrkOptFontSizeCaption10 10
#define BrkOptFontSizeCaption11 11
#define BrkOptFontSizeCaption12 12
#define BrkOptFontSizeCaption13 13
#define BrkOptFontSizeCaption14 14
#define BrkOptFontSizeBody15 15
#define BrkOptFontSizeBody16 16
#define BrkOptFontSizeBody18 18
#define BrkOptFontSizeBody20 20
#define BrkOptFontSizeBody22 22
#define BrkOptFontSizeHeading24 24
#define BrkOptFontSizeHeading28 28
#define BrkOptFontSizeHeading32 32
#define BrkOptFontSizeHeading42 42
#define BrkOptFontSizeHeading48 48
#define BrkOptFontSizeDisplay56 56
#define BrkOptFontSizeDisplay72 72
#define BrkOptLetterSpacingTight -2%
#define BrkOptLetterSpacingRegular 0%
#define BrkOptLetterSpacingLoose 2%
#define BrkOptLetterSpacingXLoose 4%
#define BrkOptParagraphSpacingNone 0
#define BrkOptParagraphSpacingBody 8%
#define BrkOptParagraphSpacingHeading 12%
#define BrkOptParagraphSpacingDisplay 16%
#define BrkOptTextTransformNone none
#define BrkOptTextTransformLowercase lowercase
#define BrkOptTextTransformUppercase uppercase
#define BrkOptTextTransformCapitalize capitalize
#define BrkOptTextDecorationNone none
#define BrkOptSizeXs 4
#define BrkOptSizeSm 8
#define BrkOptSizeMd 16
#define BrkOptSizeLg 24
#define BrkOptBorderRadiusNone 0
#define BrkOptBorderRadius3xs 1
#define BrkOptBorderRadius2xs 2
#define BrkOptBorderRadiusXs 4
#define BrkOptBorderRadiusSm 8
#define BrkOptBorderRadiusMd 16
#define BrkOptBorderRadiusLg 24
#define BrkOptBorderWidthNone 0
#define BrkOptBorderWidthXs 1
#define BrkOptBorderWidthSm 2
#define BrkOptBorderWidthMd 4
#define BrkOptBoxShadowNoneX 0
#define BrkOptBoxShadowNoneY 0
#define BrkOptBoxShadowNoneBlur 0
#define BrkOptBoxShadowNoneSpread 0
#define BrkOptBoxShadowNoneColor #000000
#define BrkOptBoxShadowNoneType dropShadow
#define BrkOptBoxShadowElevationSoftX 0
#define BrkOptBoxShadowElevationSoftY 2
#define BrkOptBoxShadowElevationSoftBlur 8
#define BrkOptBoxShadowElevationSoftSpread 0
#define BrkOptBoxShadowElevationSoftColor #e6e6e6
#define BrkOptBoxShadowElevationSoftType dropShadow
#define BrkOptBoxShadowElevationStrongX 0
#define BrkOptBoxShadowElevationStrongY 7
#define BrkOptBoxShadowElevationStrongBlur 29
#define BrkOptBoxShadowElevationStrongSpread 0
#define BrkOptBoxShadowElevationStrongColor #e6e6e6
#define BrkOptBoxShadowElevationStrongType dropShadow
#define BrkOptBoxShadowJelLqMainSmX 3px
#define BrkOptBoxShadowJelLqMainSmY 3px
#define BrkOptBoxShadowJelLqMainSmBlur 0
#define BrkOptBoxShadowJelLqMainSmSpread 0
#define BrkOptBoxShadowJelLqMainSmColor #192872
#define BrkOptBoxShadowJelLqMainSmType dropShadow
#define BrkOptBoxShadowJelLqMainMdX 5px
#define BrkOptBoxShadowJelLqMainMdY 5px
#define BrkOptBoxShadowJelLqMainMdBlur 0
#define BrkOptBoxShadowJelLqMainMdSpread 0
#define BrkOptBoxShadowJelLqMainMdColor #192872
#define BrkOptBoxShadowJelLqMainMdType dropShadow
#define BrkOptBoxShadowJelJelMainSmX 3px
#define BrkOptBoxShadowJelJelMainSmY 3px
#define BrkOptBoxShadowJelJelMainSmBlur 0
#define BrkOptBoxShadowJelJelMainSmSpread 0
#define BrkOptBoxShadowJelJelMainSmColor #0b5db7
#define BrkOptBoxShadowJelJelMainSmType dropShadow
#define BrkOptBoxShadowJelNeutralSmX 3px
#define BrkOptBoxShadowJelNeutralSmY 3px
#define BrkOptBoxShadowJelNeutralSmBlur 0
#define BrkOptBoxShadowJelNeutralSmSpread 0
#define BrkOptBoxShadowJelNeutralSmColor #ffffff
#define BrkOptBoxShadowJelNeutralSmType dropShadow
#define BrkOptSpaceSmall1 1
#define BrkOptSpaceSmall2 2
#define BrkOptSpaceSmall3 3
#define BrkOptSpaceSmall4 4
#define BrkOptSpaceSmall5 5
#define BrkOptSpaceSmall8 8
#define BrkOptSpaceSmall10 10
#define BrkOptSpaceSmall12 12
#define BrkOptSpaceSmall15 15
#define BrkOptSpaceSmall16 16
#define BrkOptSpaceSmallNone 0
#define BrkOptSpaceMedium20 20
#define BrkOptSpaceMedium30 30

