
//
// tokens.h
//

// Do not edit directly
// Generated on Thu, 25 Aug 2022 19:54:18 GMT


#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>

#define BrkInteractiveOutlineColorFocusStandard #c9ff00
#define BrkInteractiveOutlineColorFocusInverted #c9ff00
#define BrkInteractiveOutlineOffset 5
#define BrkButtonTertiaryBoxShadowDefaultStandardX 0
#define BrkButtonTertiaryBoxShadowDefaultStandardY 0
#define BrkButtonTertiaryBoxShadowDefaultStandardBlur 0
#define BrkButtonTertiaryBoxShadowDefaultStandardSpread 0
#define BrkButtonTertiaryBoxShadowDefaultStandardColor #000000
#define BrkButtonTertiaryBoxShadowDefaultStandardType dropShadow
#define BrkButtonTertiaryBoxShadowDefaultInvertedX 0
#define BrkButtonTertiaryBoxShadowDefaultInvertedY 0
#define BrkButtonTertiaryBoxShadowDefaultInvertedBlur 0
#define BrkButtonTertiaryBoxShadowDefaultInvertedSpread 0
#define BrkButtonTertiaryBoxShadowDefaultInvertedColor #000000
#define BrkButtonTertiaryBoxShadowDefaultInvertedType dropShadow
#define BrkButtonTertiaryBoxShadowHoverStandardX 0
#define BrkButtonTertiaryBoxShadowHoverStandardY 0
#define BrkButtonTertiaryBoxShadowHoverStandardBlur 0
#define BrkButtonTertiaryBoxShadowHoverStandardSpread 0
#define BrkButtonTertiaryBoxShadowHoverStandardColor #000000
#define BrkButtonTertiaryBoxShadowHoverStandardType dropShadow
#define BrkButtonTertiaryBoxShadowHoverInvertedX 0
#define BrkButtonTertiaryBoxShadowHoverInvertedY 0
#define BrkButtonTertiaryBoxShadowHoverInvertedBlur 0
#define BrkButtonTertiaryBoxShadowHoverInvertedSpread 0
#define BrkButtonTertiaryBoxShadowHoverInvertedColor #000000
#define BrkButtonTertiaryBoxShadowHoverInvertedType dropShadow
#define BrkButtonTertiaryBoxShadowFocusStandardX 0
#define BrkButtonTertiaryBoxShadowFocusStandardY 0
#define BrkButtonTertiaryBoxShadowFocusStandardBlur 0
#define BrkButtonTertiaryBoxShadowFocusStandardSpread 0
#define BrkButtonTertiaryBoxShadowFocusStandardColor #000000
#define BrkButtonTertiaryBoxShadowFocusStandardType dropShadow
#define BrkButtonTertiaryBoxShadowFocusInvertedX 0
#define BrkButtonTertiaryBoxShadowFocusInvertedY 0
#define BrkButtonTertiaryBoxShadowFocusInvertedBlur 0
#define BrkButtonTertiaryBoxShadowFocusInvertedSpread 0
#define BrkButtonTertiaryBoxShadowFocusInvertedColor #000000
#define BrkButtonTertiaryBoxShadowFocusInvertedType dropShadow
#define BrkButtonPrimaryBorderWidth 0
#define BrkButtonSecondaryBorderWidth 0
#define BrkButtonTertiaryBorderWidth 0
#define BrkButtonIconBorderWidth 0
#define BrkButtonOpacityDisabled 50%
#define BrkButtonBorderRadius 0
#define BrkinteractiveOutlineWidth 2
#define BrkButtonTertiarySmLabelFontFamily Roboto Condensed
#define BrkButtonTertiarySmLabelFontWeight Bold
#define BrkButtonTertiarySmLabelLineHeight 85%
#define BrkButtonTertiarySmLabelFontSize 14
#define BrkButtonTertiarySmLabelLetterSpacing 2%
#define BrkButtonTertiarySmLabelParagraphSpacing 0
#define BrkButtonTertiarySmLabelTextDecoration none
#define BrkButtonTertiarySmLabelTextCase uppercase
#define BrkButtonTertiaryMdLabelFontFamily Roboto Condensed
#define BrkButtonTertiaryMdLabelFontWeight Bold
#define BrkButtonTertiaryMdLabelLineHeight 85%
#define BrkButtonTertiaryMdLabelFontSize 24
#define BrkButtonTertiaryMdLabelLetterSpacing 2%
#define BrkButtonTertiaryMdLabelParagraphSpacing 0
#define BrkButtonTertiaryMdLabelTextDecoration none
#define BrkButtonTertiaryMdLabelTextCase uppercase
#define BrkButtonTertiaryLgLabelFontFamily Roboto Condensed
#define BrkButtonTertiaryLgLabelFontWeight Bold
#define BrkButtonTertiaryLgLabelLineHeight 85%
#define BrkButtonTertiaryLgLabelFontSize 28
#define BrkButtonTertiaryLgLabelLetterSpacing 2%
#define BrkButtonTertiaryLgLabelParagraphSpacing 0
#define BrkButtonTertiaryLgLabelTextDecoration none
#define BrkButtonTertiaryLgLabelTextCase uppercase
#define BrkButtonTertiaryXlLabelFontFamily Roboto Condensed
#define BrkButtonTertiaryXlLabelFontWeight Bold
#define BrkButtonTertiaryXlLabelLineHeight 85%
#define BrkButtonTertiaryXlLabelFontSize 32
#define BrkButtonTertiaryXlLabelLetterSpacing 2%
#define BrkButtonTertiaryXlLabelParagraphSpacing 0
#define BrkButtonTertiaryXlLabelTextDecoration none
#define BrkButtonTertiaryXlLabelTextCase uppercase
#define BrkButtonTertiaryFontColorDefaultStandard #000000
#define BrkButtonTertiaryFontColorDefaultInverted #000000
#define BrkButtonTertiaryBackgroundColorDefaultStandard #ffffff
#define BrkButtonTertiaryBackgroundColorDefaultInverted #ffffff
#define BrkButtonTertiaryBorderColorDefaultStandard transparent
#define BrkButtonTertiaryBorderColorDefaultInverted transparent
#define BrkButtonTertiaryFontColorHoverStandard #000000
#define BrkButtonTertiaryFontColorHoverInverted #000000
#define BrkButtonTertiaryBackgroundColorHoverStandard #c9ff00
#define BrkButtonTertiaryBackgroundColorHoverInverted #c9ff00
#define BrkButtonTertiaryBorderColorHoverStandard transparent
#define BrkButtonTertiaryBorderColorHoverInverted transparent
#define BrkButtonTertiaryFontColorFocusStandard #000000
#define BrkButtonTertiaryFontColorFocusInverted #000000
#define BrkButtonTertiaryBackgroundColorFocusStandard #c9ff00
#define BrkButtonTertiaryBackgroundColorFocusInverted #c9ff00
#define BrkButtonTertiaryBorderColorFocusStandard transparent
#define BrkButtonTertiaryBorderColorFocusInverted transparent
#define BrkButtonTertiarySmPaddingVertical 5
#define BrkButtonTertiarySmPaddingHorizontal 15
#define BrkButtonTertiaryMdPaddingVertical 10
#define BrkButtonTertiaryMdPaddingHorizontal 30
#define BrkButtonTertiaryLgPaddingVertical 15
#define BrkButtonTertiaryLgPaddingHorizontal 45
#define BrkButtonTertiaryXlPaddingVertical 20
#define BrkButtonTertiaryXlPaddingHorizontal 60
#define BrkJackpotHeroSmHeadingFontFamily Roboto Condensed
#define BrkJackpotHeroSmHeadingFontWeight Bold
#define BrkJackpotHeroSmHeadingLineHeight 100%
#define BrkJackpotHeroSmHeadingFontSize 9
#define BrkJackpotHeroSmHeadingLetterSpacing 2%
#define BrkJackpotHeroSmHeadingParagraphSpacing 0
#define BrkJackpotHeroSmHeadingTextDecoration none
#define BrkJackpotHeroSmHeadingTextCase uppercase
#define BrkJackpotHeroSmBodyFontFamily Roboto Condensed
#define BrkJackpotHeroSmBodyFontWeight Bold
#define BrkJackpotHeroSmBodyLineHeight 100%
#define BrkJackpotHeroSmBodyFontSize 12
#define BrkJackpotHeroSmBodyLetterSpacing 0%
#define BrkJackpotHeroSmBodyParagraphSpacing 0
#define BrkJackpotHeroSmBodyTextDecoration none
#define BrkJackpotHeroSmBodyTextCase uppercase
#define BrkJackpotHeroSmContentGap 16
#define BrkJackpotHeroSmPaddingHorizontal 10
#define BrkJackpotHeroSmAmountDigitMargin 1
#define BrkJackpotHeroSmAmountGroupMargin 5
#define BrkJackpotHeroSmHeight 36
#define BrkJackpotHeroSmAmountDigitHeight 20
#define BrkJackpotHeroSmAmountDigitWidth 12
#define BrkJackpotHeroMdHeadingFontFamily Roboto Condensed
#define BrkJackpotHeroMdHeadingFontWeight Regular
#define BrkJackpotHeroMdHeadingLineHeight 100%
#define BrkJackpotHeroMdHeadingFontSize 16
#define BrkJackpotHeroMdHeadingLetterSpacing 2%
#define BrkJackpotHeroMdHeadingParagraphSpacing 0
#define BrkJackpotHeroMdHeadingTextDecoration none
#define BrkJackpotHeroMdHeadingTextCase uppercase
#define BrkJackpotHeroMdBodyFontFamily Roboto Condensed
#define BrkJackpotHeroMdBodyFontWeight Regular
#define BrkJackpotHeroMdBodyLineHeight 100%
#define BrkJackpotHeroMdBodyFontSize 20
#define BrkJackpotHeroMdBodyLetterSpacing 0%
#define BrkJackpotHeroMdBodyParagraphSpacing 0
#define BrkJackpotHeroMdBodyTextDecoration none
#define BrkJackpotHeroMdBodyTextCase uppercase
#define BrkJackpotHeroMdContentGap 16
#define BrkJackpotHeroMdPaddingHorizontal 16
#define BrkJackpotHeroMdAmountDigitMargin 2
#define BrkJackpotHeroMdAmountGroupMargin 6
#define BrkJackpotHeroMdHeight 60
#define BrkJackpotHeroMdAmountDigitHeight 30
#define BrkJackpotHeroMdAmountDigitWidth 18
#define BrkJackpotHeroLgHeadingFontFamily Roboto Condensed
#define BrkJackpotHeroLgHeadingFontWeight Regular
#define BrkJackpotHeroLgHeadingLineHeight 100%
#define BrkJackpotHeroLgHeadingFontSize 20
#define BrkJackpotHeroLgHeadingLetterSpacing 2%
#define BrkJackpotHeroLgHeadingParagraphSpacing 0
#define BrkJackpotHeroLgHeadingTextDecoration none
#define BrkJackpotHeroLgHeadingTextCase uppercase
#define BrkJackpotHeroLgBodyFontFamily Roboto Condensed
#define BrkJackpotHeroLgBodyFontWeight Regular
#define BrkJackpotHeroLgBodyLineHeight 100%
#define BrkJackpotHeroLgBodyFontSize 24
#define BrkJackpotHeroLgBodyLetterSpacing 0%
#define BrkJackpotHeroLgBodyParagraphSpacing 0
#define BrkJackpotHeroLgBodyTextDecoration none
#define BrkJackpotHeroLgBodyTextCase uppercase
#define BrkJackpotHeroLgContentGap 24
#define BrkJackpotHeroLgPaddingHorizontal 24
#define BrkJackpotHeroLgAmountDigitMargin 3
#define BrkJackpotHeroLgAmountGroupMargin 8
#define BrkJackpotHeroLgHeight 72
#define BrkJackpotHeroLgAmountDigitHeight 40
#define BrkJackpotHeroLgAmountDigitWidth 24
#define BrkJackpotHeroXlHeadingFontFamily Roboto Condensed
#define BrkJackpotHeroXlHeadingFontWeight Regular
#define BrkJackpotHeroXlHeadingLineHeight 100%
#define BrkJackpotHeroXlHeadingFontSize 22
#define BrkJackpotHeroXlHeadingLetterSpacing 2%
#define BrkJackpotHeroXlHeadingParagraphSpacing 0
#define BrkJackpotHeroXlHeadingTextDecoration none
#define BrkJackpotHeroXlHeadingTextCase uppercase
#define BrkJackpotHeroXlBodyFontFamily Roboto Condensed
#define BrkJackpotHeroXlBodyFontWeight Regular
#define BrkJackpotHeroXlBodyLineHeight 100%
#define BrkJackpotHeroXlBodyFontSize 28
#define BrkJackpotHeroXlBodyLetterSpacing 0%
#define BrkJackpotHeroXlBodyParagraphSpacing 0
#define BrkJackpotHeroXlBodyTextDecoration none
#define BrkJackpotHeroXlBodyTextCase uppercase
#define BrkJackpotHeroXlPaddingHorizontal 24
#define BrkJackpotHeroXlContentGap 24
#define BrkJackpotHeroXlAmountDigitMargin 4
#define BrkJackpotHeroXlAmountGroupMargin 10
#define BrkJackpotHeroXlHeight 72
#define BrkJackpotHeroXlAmountDigitHeight 44
#define BrkJackpotHeroXlAmountDigitWidth 28
#define BrkJackpotHeroHeadingFontColorStandard #c9ff00
#define BrkJackpotHeroBodyFontColorStandard #ffffff
#define BrkJackpotHeroBodyFontColorInverted #ffffff
#define BrkJackpotHeroBodyBoxBackgroundColorStandard #000000
#define BrkJackpotHeroBodyBoxBorderColorStandard #ffffff
#define BrkJackpotHeroBackgroundColorStandard #000000
#define BrkJackpotHeroAmountDigitBorderRadius 0
#define BrkJackpotHeroAmountDigitBorderWidth 1
#define BrkCardHeroSmPretitleFontFamily Roboto Condensed
#define BrkCardHeroSmPretitleFontWeight Regular
#define BrkCardHeroSmPretitleLineHeight 9
#define BrkCardHeroSmPretitleFontSize 9
#define BrkCardHeroSmPretitleLetterSpacing 2%
#define BrkCardHeroSmPretitleParagraphSpacing 0
#define BrkCardHeroSmPretitleTextDecoration none
#define BrkCardHeroSmPretitleTextCase uppercase
#define BrkCardHeroSmHeadingFontFamily Roboto Condensed
#define BrkCardHeroSmHeadingFontWeight Bold
#define BrkCardHeroSmHeadingLineHeight 100%
#define BrkCardHeroSmHeadingFontSize 14
#define BrkCardHeroSmHeadingLetterSpacing 0%
#define BrkCardHeroSmHeadingParagraphSpacing 0
#define BrkCardHeroSmHeadingTextDecoration none
#define BrkCardHeroSmHeadingTextCase uppercase
#define BrkCardHeroSmBodyFontFamily Roboto Condensed
#define BrkCardHeroSmBodyFontWeight Regular
#define BrkCardHeroSmBodyLineHeight 85%
#define BrkCardHeroSmBodyFontSize 8
#define BrkCardHeroSmBodyLetterSpacing 2%
#define BrkCardHeroSmBodyParagraphSpacing 0
#define BrkCardHeroSmBodyTextDecoration none
#define BrkCardHeroSmBodyTextCase uppercase
#define BrkCardHeroSmImageHeight 180
#define BrkCardHeroSmPaddingHorizontal 10
#define BrkCardHeroSmPaddingVertical 10
#define BrkCardHeroSmHeadingMarginVertical 4
#define BrkCardHeroSmContentGap 16
#define BrkCardHeroMdPretitleFontFamily Roboto Condensed
#define BrkCardHeroMdPretitleFontWeight Regular
#define BrkCardHeroMdPretitleLineHeight 12
#define BrkCardHeroMdPretitleFontSize 12
#define BrkCardHeroMdPretitleLetterSpacing 2%
#define BrkCardHeroMdPretitleParagraphSpacing 0
#define BrkCardHeroMdPretitleTextDecoration none
#define BrkCardHeroMdPretitleTextCase uppercase
#define BrkCardHeroMdHeadingFontFamily Roboto Condensed
#define BrkCardHeroMdHeadingFontWeight Bold
#define BrkCardHeroMdHeadingLineHeight 100%
#define BrkCardHeroMdHeadingFontSize 24
#define BrkCardHeroMdHeadingLetterSpacing 0%
#define BrkCardHeroMdHeadingParagraphSpacing 0
#define BrkCardHeroMdHeadingTextDecoration none
#define BrkCardHeroMdHeadingTextCase uppercase
#define BrkCardHeroMdBodyFontFamily Roboto Condensed
#define BrkCardHeroMdBodyFontWeight Regular
#define BrkCardHeroMdBodyLineHeight 85%
#define BrkCardHeroMdBodyFontSize 13
#define BrkCardHeroMdBodyLetterSpacing 2%
#define BrkCardHeroMdBodyParagraphSpacing 0
#define BrkCardHeroMdBodyTextDecoration none
#define BrkCardHeroMdBodyTextCase uppercase
#define BrkCardHeroMdImageHeight 270
#define BrkCardHeroMdPaddingHorizontal 16
#define BrkCardHeroMdPaddingVertical 16
#define BrkCardHeroMdHeadingMarginVertical 4
#define BrkCardHeroMdContentGap 24
#define BrkCardHeroLgPretitleFontFamily Roboto Condensed
#define BrkCardHeroLgPretitleFontWeight Regular
#define BrkCardHeroLgPretitleLineHeight 16
#define BrkCardHeroLgPretitleFontSize 16
#define BrkCardHeroLgPretitleLetterSpacing 2%
#define BrkCardHeroLgPretitleParagraphSpacing 0
#define BrkCardHeroLgPretitleTextDecoration none
#define BrkCardHeroLgPretitleTextCase uppercase
#define BrkCardHeroLgHeadingFontFamily Roboto Condensed
#define BrkCardHeroLgHeadingFontWeight Bold
#define BrkCardHeroLgHeadingLineHeight 100%
#define BrkCardHeroLgHeadingFontSize 28
#define BrkCardHeroLgHeadingLetterSpacing 0%
#define BrkCardHeroLgHeadingParagraphSpacing 0
#define BrkCardHeroLgHeadingTextDecoration none
#define BrkCardHeroLgHeadingTextCase uppercase
#define BrkCardHeroLgBodyFontFamily Roboto Condensed
#define BrkCardHeroLgBodyFontWeight Regular
#define BrkCardHeroLgBodyLineHeight 85%
#define BrkCardHeroLgBodyFontSize 14
#define BrkCardHeroLgBodyLetterSpacing 2%
#define BrkCardHeroLgBodyParagraphSpacing 0
#define BrkCardHeroLgBodyTextDecoration none
#define BrkCardHeroLgBodyTextCase uppercase
#define BrkCardHeroLgImageHeight 270
#define BrkCardHeroLgPaddingHorizontal 24
#define BrkCardHeroLgPaddingVertical 24
#define BrkCardHeroLgHeadingMarginVertical 8
#define BrkCardHeroLgContentGap 24
#define BrkCardHeroXlPretitleFontFamily Roboto Condensed
#define BrkCardHeroXlPretitleFontWeight Regular
#define BrkCardHeroXlPretitleLineHeight 20
#define BrkCardHeroXlPretitleFontSize 20
#define BrkCardHeroXlPretitleLetterSpacing 2%
#define BrkCardHeroXlPretitleParagraphSpacing 0
#define BrkCardHeroXlPretitleTextDecoration none
#define BrkCardHeroXlPretitleTextCase uppercase
#define BrkCardHeroXlHeadingFontFamily Roboto Condensed
#define BrkCardHeroXlHeadingFontWeight Bold
#define BrkCardHeroXlHeadingLineHeight 100%
#define BrkCardHeroXlHeadingFontSize 36
#define BrkCardHeroXlHeadingLetterSpacing 0%
#define BrkCardHeroXlHeadingParagraphSpacing 0
#define BrkCardHeroXlHeadingTextDecoration none
#define BrkCardHeroXlHeadingTextCase uppercase
#define BrkCardHeroXlBodyFontFamily Roboto Condensed
#define BrkCardHeroXlBodyFontWeight Regular
#define BrkCardHeroXlBodyLineHeight 85%
#define BrkCardHeroXlBodyFontSize 18
#define BrkCardHeroXlBodyLetterSpacing 2%
#define BrkCardHeroXlBodyParagraphSpacing 0
#define BrkCardHeroXlBodyTextDecoration none
#define BrkCardHeroXlBodyTextCase uppercase
#define BrkCardHeroXlImageHeight 320
#define BrkCardHeroXlPaddingHorizontal 24
#define BrkCardHeroXlPaddingVertical 24
#define BrkCardHeroXlHeadingMarginVertical 8
#define BrkCardHeroXlContentGap 16
#define BrkCardHeroHeadingFontColorStandard #ffffff
#define BrkCardHeroSubheadingFontColorStandard #000000
#define BrkCardHeroBodyFontColorStandard #000000
#define BrkCardHeroBackgroundColorStandard #e41f1f
#define BrkCardHeroBorderColorStandard #000000
#define BrkCardHeroBorderWidth 1
#define BrkCardHeroBorderRadius 0
#define BrkCardHeroBoxShadowDefaultStandardX 0
#define BrkCardHeroBoxShadowDefaultStandardY 0
#define BrkCardHeroBoxShadowDefaultStandardBlur 0
#define BrkCardHeroBoxShadowDefaultStandardSpread 0
#define BrkCardHeroBoxShadowDefaultStandardColor #000000
#define BrkCardHeroBoxShadowDefaultStandardType dropShadow
#define BrkCardHeroBoxShadowDefaultHoverX 0
#define BrkCardHeroBoxShadowDefaultHoverY 2
#define BrkCardHeroBoxShadowDefaultHoverBlur 8
#define BrkCardHeroBoxShadowDefaultHoverSpread 0
#define BrkCardHeroBoxShadowDefaultHoverColor #1a1a1a
#define BrkCardHeroBoxShadowDefaultHoverType dropShadow
#define BrkButtonPrimarySmLabelFontFamily Roboto Condensed
#define BrkButtonPrimarySmLabelFontWeight Bold
#define BrkButtonPrimarySmLabelLineHeight 85%
#define BrkButtonPrimarySmLabelFontSize 14
#define BrkButtonPrimarySmLabelLetterSpacing 2%
#define BrkButtonPrimarySmLabelParagraphSpacing 0
#define BrkButtonPrimarySmLabelTextDecoration none
#define BrkButtonPrimarySmLabelTextCase uppercase
#define BrkButtonPrimaryMdLabelFontFamily Roboto Condensed
#define BrkButtonPrimaryMdLabelFontWeight Bold
#define BrkButtonPrimaryMdLabelLineHeight 85%
#define BrkButtonPrimaryMdLabelFontSize 24
#define BrkButtonPrimaryMdLabelLetterSpacing 2%
#define BrkButtonPrimaryMdLabelParagraphSpacing 0
#define BrkButtonPrimaryMdLabelTextDecoration none
#define BrkButtonPrimaryMdLabelTextCase uppercase
#define BrkButtonPrimaryLgLabelFontFamily Roboto Condensed
#define BrkButtonPrimaryLgLabelFontWeight Bold
#define BrkButtonPrimaryLgLabelLineHeight 85%
#define BrkButtonPrimaryLgLabelFontSize 28
#define BrkButtonPrimaryLgLabelLetterSpacing 2%
#define BrkButtonPrimaryLgLabelParagraphSpacing 0
#define BrkButtonPrimaryLgLabelTextDecoration none
#define BrkButtonPrimaryLgLabelTextCase uppercase
#define BrkButtonPrimaryXlLabelFontFamily Roboto Condensed
#define BrkButtonPrimaryXlLabelFontWeight Bold
#define BrkButtonPrimaryXlLabelLineHeight 85%
#define BrkButtonPrimaryXlLabelFontSize 32
#define BrkButtonPrimaryXlLabelLetterSpacing 2%
#define BrkButtonPrimaryXlLabelParagraphSpacing 0
#define BrkButtonPrimaryXlLabelTextDecoration none
#define BrkButtonPrimaryXlLabelTextCase uppercase

